theme: jekyll-theme-minimal
title: "EUCA: End-User-Centered Explainable AI Framework"
description: A practical prototyping tool to design explainable AI for non-technical end-users.
author: Weina Jin

navigation:
  - title: EUCA Homepage
    url: /
  - title: End-User-Friendly Explanatory Forms
    url: /explanatory_form.html
    subfolderitems:
      - Feature attribute
        url: /explanatory_form.html#fa
  - title: Explanation Needs
    url: /need


avatar: /fig/euca_logo.png

social-network-links:
  email: "weinaj@sfu.ca"
  github: weinajin

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "end-user-xai.github.io"
