theme: jekyll-theme-minimal
title: "EUCA: End-User-Centered Explainable AI Framework"
description: A practical prototyping tool to design explainable AI for non-technical end-users.
author: Weina Jin

navigation:
  - title: EUCA Homepage
    url: /
  - title: End-User-Friendly Explanatory Forms
    url: /explanatory_form.html
    subfolderitems:
      - Feature attribute
  - title: Explanation Needs
    url: /need

logo: /assets/img/favicon.png













