theme: jekyll-theme-cayman
title: "<a href="https://weina.me/end-user-xai">EUCA: <ins>E</ins>nd-<ins>U</ins>ser-<ins>C</ins>entered Explainable <ins>A</ins>I Framework</a>"
description: A practical prototyping tool to design explainable AI for non-technical end-users.
author: Weina Jin

navbar-links:
  EUCA Homepage: "https://weina.me/end-user-xai/"
  Resources:
    - End-User-Friendly Explanatory Forms: "/explanatory_form"
    - Explanation Needs: "/need"


avatar: "fig/euca_logo.png"

social-network-links:
  email: "weinaj@sfu.ca"
  github: weinajin

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "end-user-xai.github.io"
