theme: jekyll-theme-cayman
title: "The <ins>E</ins>nd-<ins>U</ins>ser-<ins>C</ins>entered Explainable <ins>A</ins>I Framework"
description: A practical prototyping tool to design explainable AI for non-technical end-users.